include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - path/to/excluded/files/** # 解析から除外するファイルやディレクトリを指定
  errors:
    unused_import: error # エラーとして扱う
    deprecated_member_use: warning # 警告として扱う
    unused_local_variable: ignore # 特定の警告やエラーを無視する

linter:
  rules:
    - avoid_print # print文の使用を避ける
    - constant_identifier_names # 定数名はすべて大文字でスネークケースを使う
    - avoid_as # 'as' キーワードの使用を避ける
    - avoid_empty_else # 空のelse文を避ける
    - camel_case_types # クラス名はキャメルケースを使う
    - file_names # ファイル名はスネークケースで
    - flutter_style_todos # FlutterスタイルのTODOコメント

# 以下はFlutter特有の解析オプション
flutter:
  uses-material-design: true # Materialデザインのアイコンとフォントを使用するかどうか